### ISSUE TITLE
Exception not included in std. log4net property ExceptionString

### ISSUE THREAD

**Issue by pihalve** [TorbenRahbekKoch/LogBridge#3]
Right now LogBridge uses a custom property for holding the exception when specifying an exception in calls to Error() method. However, log4net seems to have the ExceptionString property for this, which will make the exception part of the log message. The problem with having the exception in a custom property is you have to explicitly specify it in the layout->conversionPattern configuration, like %property{exception}. While this works fine for error/fatal level messages, it is not great for messages at other levels for which "(null)" will be output.
I believe the change to use ExceptionString will be relevant for both Log4Net and UmbracoLog4Net implementations.

**Comment by TorbenRahbekKoch** [comment]
I whole-heartedly agree - this will be fixed in the very soon upcoming 1.3.
