### ISSUE TITLE
Reference to vulnerable log4net

### ISSUE THREAD

**Issue by pihalve** [TorbenRahbekKoch/LogBridge#6]
Hey. Just wanted to mention that LogBridge.Log4Net references a version of log4net with a high severity security issue (as described here: https://security.snyk.io/vuln/SNYK-DOTNET-LOG4NET-568897)

**Comment by TorbenRahbekKoch** [comment]
Thanks! Will fix!

**Comment by TorbenRahbekKoch** [comment]
It took some time, but it has now been fixed in version 1.6.0 :)
